# Generated by Django 4.2.4 on 2023-11-08 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("developers", "0003_project"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project", old_name="dev_name", new_name="developer",
        ),
        migrations.RenameField(
            model_name="project", old_name="name", new_name="project_name",
        ),
    ]
