# Generated by Django 4.2.4 on 2023-11-13 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("developers", "0004_rename_dev_name_project_developer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="developer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="developers.developers"
            ),
        ),
    ]
