# Generated by Django 4.2.4 on 2023-11-15 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("developers", "0005_alter_project_developer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="developer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="developers.developers",
            ),
        ),
    ]
